version: '3'
services:
  api:
    build: .
    container_name: sasquatch_api
    volumes:
      - ./src:/srv/sasquatch_api/src
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    working_dir: /srv/sasquatch_api
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    command: mysqld --user=root --verbose
    volumes:
       - ./schemadump.sql:/docker-entrypoint-initdb.d/schemadump.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
